---
- name: Check Mikrotik
  hosts: ros_routers
  # connection: network_cli
  gather_facts: false
  tasks:
    - name: run command on remote devices
      community.routeros.command:
        commands: /system resource print
      register: mtkupchk
    - debug:
        var: mtkupchk.stdout_lines

#    - name: collect all factshttps://github.com/iserbkin/ansible-test/blob/master/play.yml
#      community.routeros.facts:
#        gather_subset: all
#    - debug:
#        msg: "{{ansible_net_model}}"
